name: Staging build check
run-name: Staging Build Check by @${{ github.actor }}:${{ github.event_name }}

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Install dependencies and build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      - run: npm install